apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-api-deploy
  namespace: employee-api

spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-api

  template:
    metadata:
      labels:
        app: employee-api

    spec:
      containers:
      - name: employee-api
        image: fastapi-app:v1.0
        imagePullPolicy: Never

        ports:
        - containerPort: 8000

        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"